const mongoos=require("mongoose")

const clientSchema= new mongoos.Schema({
    FirstName:{
        type:String,
        required:true
    },
    LastName:{
        type:String,
        required:false
    },
    MobileNumber:{
        type:String,
        required:true
    },
    Email:{
        type:String,
        required:true
    },
    Gender:{
        type:String,
        required:false
    },
    DateofBirth:{
        type:String,
        required:false
    },
    Anniversary:{
        type:String,
        required:false
    },
    Occupation:{
        type:String,
        required:false
    },
    ClientSource:{
        type:String,
        required:false
    },
    ClientType:{
        type:String,
        required:false
    },
    PAN:{
        type:String,
        required:false
    },
    GST:{
        type:String,
        required:false
    },
    CompanyLegalName:{
        type:String,
        required:false
    },
    CompanyTradeName:{
        type:String,
        required:false
    },
    BillingAddress:{
        type:String,
        required:false
    },
    ShippingAddress:{
        type:String,
        required:false
    },
    EmailNotification:{
        type:Boolean,
        required:true
    },
    EmailMarketingNotification:{
        type:Boolean,
        required:true
    },
    ParentBranchId:{
        type:String,
        required:true
    },
    Memberships:{
        type:Object,
        required:false
    },
})

module.exports=mongoos.model('Client',clientSchema)