const mongoos=require("mongoose")

const membershipsSchema= new mongoos.Schema({
    MembershipName:{
        type:String,
        required:true
    },
    MembershipDescription:{
        type:String,
        required:true
    },
    Services:{
        type:Array,
        required:true
    },
    MembershipCost:{
        type:Number,
        required:true
    },
    SellingCost:{
        type:Number,
        required:true
    },
    Taxrate:{
        type:Number,
        required:true
    },
    HsnCode:{
        type:String,
        required:true
    },
    active:{
        type:Boolean,
        required:true
    },
    Branch:{
        type:String,
        required:true
    },
    isunlimited:{
        type:Boolean,
        required:true
    },
    count:{
        type:Number,
        required:true
    },
    validity:{
        type:Number,
        required:true
    },
})

module.exports=mongoos.model('memberships',membershipsSchema)